
---


# 游녦 Bienvenida y gu칤a r치pida


Bienvenido/a a tu sistema RepurpOS en Debian. 游냖

Desde el equipo de Repurpose-IT te contamos que este es un espacio libre para la educaci칩n que sirve para conectar tus expectativas de aprendizaje con tu comunidad. Nuestro objetivo es que las herramientas tecnol칩gicas sean de libre acceso. Esperamos que este sistema te brinde esa libertad. 游꺔


A continuaci칩n te contamos qu칠 encontrar치s en este dispositivo. 游닍

Hemos hecho una selecci칩n de material autodidacta en el que podr치s encontrar diferentes recursos 칰tiles para el aprendizaje, el dise침o, la elaboraci칩n de tareas y mucho m치s. Te invitamos a que revises los programas que est치n catalogados dentro de las carpetas de arte, ciencia, escritura, geograf칤a, matem치ticas, programaci칩n, sonido, rompecabezas y una carpeta accesible a ni침os. 游꿛游빌

Adem치s, hemos hecho una selecci칩n de videos espec칤ficos destinados a que puedas aprender m치s sobre la comunidad Arhuaca y Kogui, con la finalidad de que las costumbres de tu comunidad permanezcan en tu dispositivo. Todo este material puedes encontrarlo en la carpeta "Videoteca". 游닠

Tambi칠n encontrar치s una carpeta llamada "Biblioteca" en la que podr치s encontrar herramientas que te ayuden a la redacci칩n y a la adaptaci칩n del espa침ol como segundo idioma. Util칤zala y agr칠gale lo que creas que sea necesario para tu libre aprendizaje. 游닄


춰Explora, aprende y comparte! 游 Este sistema est치 hecho para ti y tu comunidad.

<div style="margin-top: 2em; display: flex; gap: 1.5em; justify-content: center; align-items: center;">
  <a href="https://github.com/Repurpose-IT/Repurp-OS/issues" class="btn btn-primary" target="_blank" style="font-size: 1.25em; padding: 0.75em 2em;">Colabora</a>
  <a href="https://repurpose-it.github.io/Repurp-OS/" class="btn btn-success" target="_blank" style="font-size: 1.25em; padding: 0.75em 2em;">Con칩cenos</a>
</div>



